name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the 'main' branch

jobs:
  # Job 1: Run Tests (depends on the install-dependencies job)
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the version of Node.js
      # Step 3: Install dependencies (needed for tests)
      - name: Install dependencies
        run: npm install
      # Step 4: Run tests
      - name: Run tests
        run: npm test

  # Job 2: Deploy (depends on the run-tests job)
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests  # This job depends on the run-tests job
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the version of Node.js
      # Step 3: Install dependencies (needed for deployment, e.g., for building the app)
      - name: Install dependencies
        run: npm install
      # Step 4: Deploy Application (this is just an echo for demonstration)
      - name: Deploy Application
        run: |
          echo "Deployment successful! (This is just an echo for demonstration)"